### PR TITLE
feat: camel case jira tag support

### LINKED ISSUE #38: Is there a way to detect lowercase jira id?
Currently the automatic branch name detection only works if the branch has a matching `jiraPrefix`
example:
- feature-daz-1234-branch-name // does not work
- feature-DAZ-1234-branch-name // detects DAZ-1234

### PR DESCRIPTION
**Pull request by wpater**
Support for lower/camel case Jira tag in form and branch name.

Closes #38

### CODE REVIEW

**Comment by juliuscc** [comment]
Hi! Sorry for being so late with answering.

Is there a risk that this regex-pattern is too inclusive? Like if I call a branch `introduce-dynamic-checkout-2` wouldn't this be parsed as a Jira-issue?

Of course, there was always a risk of incorrectly parsing regular branches as JIRA-issues, but with all caps it is less likely.

Maybe that's fine? What do you think?

Do you have any thoughts @polarn?

**Comment by polarn** [comment]
@juliuscc The "worst case" would be getting a bad suggestion/default value for the issue, I think that could be acceptable?

**Comment by juliuscc** [comment]
Sure let's merge it then :)

**Comment by juliuscc** [comment]
Thanks a lot for the contribution @wpater! ❤️

**Pull request merged**
