### PR TITLE
feat: allow skip description and skip breaking changes

### PR DESCRIPTION
**Pull request by AlfredChow2338**
Hi, I am using this library to create commit prompt feature for my company. The feature of "description" and "breaking changes" is of no use for my current usage but I cannot find the configuration flag to disable it. So I followed the pattern of "skipScope" to create 2 new flags "skipDescription" and "skipBreaking" to override it to save more time for developers. Really appreciate all the effort that has been made by the community. I hope this can contribute to this amazing library. Thank you!

### CODE REVIEW

**Comment by juliuscc** [comment]
Thanks for providing a very clean commit. I think you covered most parts. I have a small question about `options.defaultBody`. What will happen if you don't provide a body and there is no `defaultBody`? Will it work?

**Comment by AlfredChow2338** [comment]
It works as below. I ran this version in local without any error. 

Screenshot from 2022-09-01 23-01-08 (1)

**Comment by juliuscc** [comment]
Perfect! That looks good to me 👍

**Comment by juliuscc** [comment]
Thanks for the very nice PR, and the added comment. You made it very easy for me to approve and merge 😁

**Pull request merged**
