### PR TITLE
feat: add inquirer dependency

### PR DESCRIPTION
**Pull request by laytong**
Seems it didn't need any changes to package-lock which I thought was interesting.

This fixes use of this package for yarn pnp.

### CODE REVIEW

**Comment by laytong** [comment]
fixes #35

**Comment by juliuscc** [comment]
Nice that this fixes your issues!

> Seems it didn't need any changes to package-lock which I thought was interesting.

I assume this is because inquirer already was in the dependency tree, and therefore it shouldn't be any difference to `node_modules`.

One nitpick. What do you think about calling this a `fix` instead of a `feat`? I can change it myself when I merge but I want your input on it 😁

**Comment by laytong** [comment]
Fine by me :)

**Comment by juliuscc** [comment]
Great!

**Comment by laytong** [comment]
Can we cut a release for this pretty please :)

**Comment by juliuscc** [comment]
@Saeger the continuous deployment job seems to fail. Can you help us with this? I have raised a separate issue about it (#54).

**Comment by Saeger** [comment]
Looking at it

**Pull request merged**
